VerificationTest[(CodeCheckFix[#1, "Target" -> "Evaluator"] & )["f[a,g[h];b[c]"], <|"ErrorsDetected" -> True, "CodeInspector" -> <|"InspectionObjects" -> {CodeInspector`InspectionObject["GroupMissingCloser", "Missing closer.", "Fatal", <|CodeParser`Source -> {2, 2}, ConfidenceLevel -> 1.|>]}, "OverallSeverity" -> 4|>, "Success" -> True, "TotalFixes" -> 1, "LikelyFalsePositive" -> False, "SafeToEvaluate" -> True, "FixedCode" -> "f[a,g[h];b[c]]", "FixedPatterns" -> {{{"Fatal", "GroupMissingCloser"}}}, "OriginalCode" -> "f[a,g[h];b[c]"|>
	,TestID->"1_scoreAmbiguous_UT"]
VerificationTest[(CodeCheckFix[#1, "Target" -> "Evaluator"] & )["Graphics3D[{a,{b},{c,Red},ViewPoint -> {1, -2, 1}]"], <|"ErrorsDetected" -> True, "CodeInspector" -> <|"InspectionObjects" -> {CodeInspector`InspectionObject["GroupMissingCloser", "Missing closer.", "Fatal", <|CodeParser`Source -> {12, 12}, ConfidenceLevel -> 1.|>]}, "OverallSeverity" -> 4|>, "Success" -> True, "TotalFixes" -> 1, "LikelyFalsePositive" -> False, "SafeToEvaluate" -> True, "FixedCode" -> "Graphics3D[{a,{b},{c,Red}},ViewPoint -> {1, -2, 1}]", "FixedPatterns" -> {{{"Fatal", "GroupMissingCloser"}}}, "OriginalCode" -> "Graphics3D[{a,{b},{c,Red},ViewPoint -> {1, -2, 1}]"|>
	,TestID->"2_scoreAmbiguous_UT"]
VerificationTest[(CodeCheckFix[#1, "Target" -> "Evaluator"] & )["Graphics3D[{a,{b},{c,Red},ViewPoint -> Automatic]"], <|"ErrorsDetected" -> True, "CodeInspector" -> <|"InspectionObjects" -> {CodeInspector`InspectionObject["GroupMissingCloser", "Missing closer.", "Fatal", <|CodeParser`Source -> {12, 12}, ConfidenceLevel -> 1.|>]}, "OverallSeverity" -> 4|>, "Success" -> True, "TotalFixes" -> 1, "LikelyFalsePositive" -> False, "SafeToEvaluate" -> True, "FixedCode" -> "Graphics3D[{a,{b},{c,Red}},ViewPoint -> Automatic]", "FixedPatterns" -> {{{"Fatal", "GroupMissingCloser"}}}, "OriginalCode" -> "Graphics3D[{a,{b},{c,Red},ViewPoint -> Automatic]"|>
	,TestID->"3_scoreAmbiguous_UT"]
VerificationTest[(CodeCheckFix[#1, "Target" -> "Evaluator"] & )["graphics3D[{a,{b},{c,Red},ViewPoint -> Automatic]"], <|"ErrorsDetected" -> True, "CodeInspector" -> <|"InspectionObjects" -> {CodeInspector`InspectionObject["GroupMissingCloser", "Missing closer.", "Fatal", <|CodeParser`Source -> {12, 12}, ConfidenceLevel -> 1.|>]}, "OverallSeverity" -> 4|>, "Success" -> True, "TotalFixes" -> 1, "LikelyFalsePositive" -> False, "SafeToEvaluate" -> True, "FixedCode" -> "graphics3D[{a,{b},{c,Red}},ViewPoint -> Automatic]", "FixedPatterns" -> {{{"Fatal", "GroupMissingCloser"}}}, "OriginalCode" -> "graphics3D[{a,{b},{c,Red},ViewPoint -> Automatic]"|>
	,TestID->"4_scoreAmbiguous_UT"]
VerificationTest[(CodeCheckFix[#1, "Target" -> "Evaluator"] & )["Graphics3D[{a,b,{c,Red},viewPoint -> Automatic]"], <|"ErrorsDetected" -> True, "CodeInspector" -> <|"InspectionObjects" -> {CodeInspector`InspectionObject["GroupMissingCloser", "Missing closer.", "Fatal", <|CodeParser`Source -> {12, 12}, ConfidenceLevel -> 1.|>]}, "OverallSeverity" -> 4|>, "Success" -> True, "TotalFixes" -> 1, "LikelyFalsePositive" -> False, "SafeToEvaluate" -> True, "FixedCode" -> "Graphics3D[{a,b,{c,Red}},viewPoint -> Automatic]", "FixedPatterns" -> {{{"Fatal", "GroupMissingCloser"}}}, "OriginalCode" -> "Graphics3D[{a,b,{c,Red},viewPoint -> Automatic]"|>
	,TestID->"5_scoreAmbiguous_UT"]
VerificationTest[(CodeCheckFix[#1, "Target" -> "Evaluator"] & )["graphics3D[{a,b,{c,Red},viewPoint -> {1, -2, 1}]"], <|"ErrorsDetected" -> True, "CodeInspector" -> <|"InspectionObjects" -> {CodeInspector`InspectionObject["GroupMissingCloser", "Missing closer.", "Fatal", <|CodeParser`Source -> {12, 12}, ConfidenceLevel -> 1.|>]}, "OverallSeverity" -> 4|>, "Success" -> True, "TotalFixes" -> 1, "LikelyFalsePositive" -> False, "SafeToEvaluate" -> True, "FixedCode" -> "graphics3D[{a,b,{c,Red},viewPoint -> {1, -2, 1}}]", "FixedPatterns" -> {{{"Fatal", "GroupMissingCloser"}}}, "OriginalCode" -> "graphics3D[{a,b,{c,Red},viewPoint -> {1, -2, 1}]"|>
	,TestID->"6_scoreAmbiguous_UT"]