(* ::Section::Closed:: *)
(*Package Header*)
BeginPackage[ "Wolfram`Chatbook`PromptGenerators`RelatedDocumentation`" ];
Begin[ "`Private`" ];

Needs[ "Wolfram`Chatbook`"                         ];
Needs[ "Wolfram`Chatbook`PromptGenerators`Common`" ];
Needs[ "Wolfram`Chatbook`Common`"                  ];

(* ::**************************************************************************************************************:: *)
(* ::Section::Closed:: *)
(*Configuration*)
$snippetDebug                  = True;
$snippetType                   = "Text";
$documentationSnippetVersion  := $snippetVersion;
$snippetFetchBatchSize         = 15;
$baseURL                       = "https://www.wolframcloud.com/obj/wolframai-content/DocumentationSnippets";
$streamableSnippetBaseURL      = "https://www.wolframcloud.com/obj/wolframai-content/StreamableSnippets";
$documentationMarkdownBaseURL := URLBuild @ { $baseURL, $documentationSnippetVersion, "Markdown" };
$streamableSnippetTypes        = { "Documentation", "ResourceSystem" };

$rerankMethod := $rerankMethod = CurrentChatSettings[ "DocumentationRerankMethod" ];

$usePromptHeader = True;

$rerankScoreThreshold = 3;

$bestDocumentationPromptMethod := $bestDocumentationPromptMethod = CurrentChatSettings[ "RerankPromptStyle" ];
$bestDocumentationPrompt := If[ $bestDocumentationPromptMethod === "JSON",
                                $bestDocumentationPromptLarge,
                                $bestDocumentationPromptSmall
                            ];

$defaultSources = {
    "Documentation",
    "EntityValues",
    "FunctionRepository",
    "DataRepository",
    "NeuralNetRepository",
    "PacletRepository"
};

$sourceAliases = <|
    "DataRepository"      -> "DataRepositoryURIs",
    "Documentation"       -> "DocumentationURIs",
    "FunctionRepository"  -> "FunctionRepositoryURIs",
    "NeuralNetRepository" -> "NeuralNetRepositoryURIs",
    "PacletRepository"    -> "PacletRepositoryURIs"
|>;

$maxSelectedSources       = 3;
$minUnfilteredItems       = 20;
$unfilteredItemsPerSource = 25;

$filteringLLMConfig = <| (* "StopTokens" -> { "CasualChat" } *) |>; (* gpt-5.4-nano does not support stop tokens *)


$$assistantTypeTag = "Computational"|"Knowledge"|"Data"|"CasualChat";


$taskPrompt = "\
Your task is to read a chat transcript and select relevant Wolfram Language documentation snippets to help answer the \
user's latest message.";

(* ::**************************************************************************************************************:: *)
(* ::Subsection::Closed:: *)
(*$snippetVersion*)
$snippetVersion := $snippetVersion = If[ $VersionNumber >= 15.0, "15-0-0-13528852", "14-3-0-11967661" ];

$streamableSnippetVersions := $streamableSnippetVersions = <|
    "Documentation"  -> $snippetVersion,
    "ResourceSystem" -> "1.1.0"
|>;

(* The table below is generated by Scripts/UpdateDownloadMetadata.wls. Do not edit it manually. *)
(* BEGIN GENERATED: StreamableSnippetDownloadMetadata *)
(* Expected archive sizes and SHA-256 hashes for downloaded snippet archives (keyed by name and version): *)
$streamableSnippetArchiveInfo = <|
    { "Documentation" , "14-3-0-11967661" } -> { 38099319, "064bac98325395906fc65788baa1b1411ce9c1ed990a8182a42154119747f9e4" },
    { "Documentation" , "15-0-0-13528852" } -> { 37084178, "a8962c418468149bf3d57a8664051bfd567fdd645c19e3ba33675e834af61510" },
    { "ResourceSystem", "1.1.0"           } -> {  9948586, "306b693c986200479069616b24c3658331dba79075246988ae635af6f646b178" }
|>;
(* END GENERATED: StreamableSnippetDownloadMetadata *)

$streamableSnippetSizes  := AssociationMap[ streamableSnippetArchiveInfo[ #, 1 ] &, $streamableSnippetTypes ];
$streamableSnippetHashes := AssociationMap[ streamableSnippetArchiveInfo[ #, 2 ] &, $streamableSnippetTypes ];

streamableSnippetArchiveInfo[ name_String, n_Integer ] :=
    Replace[
        Lookup[ $streamableSnippetArchiveInfo, Key @ { name, $streamableSnippetVersions @ name } ],
        { info: { _, _ } :> info[[ n ]], _ :> Missing[ "NotAvailable" ] }
    ];

$snippetDownloadDeclined = False;
$snippetLockPersistence  = Infinity;

(* ::**************************************************************************************************************:: *)
(* ::Section::Closed:: *)
(*Messages*)
Chatbook::CloudDownloadError = "\
Unable to download required data from the cloud. Please try again later.";

Chatbook::SnippetDownloadDeclined = "\
Documentation resources are not available because the download was cancelled. \
Evaluate InstallDocumentationResources[] to install them.";

Chatbook::SnippetDownloadFailed = "\
Failed to download documentation resources: `1`. \
Please check your internet connection and evaluate InstallDocumentationResources[] to try again.";

Chatbook::InvalidSources = "\
Invalid value for the \"Sources\" option: `1`.";

Chatbook::InvalidMaxSources = "\
Invalid value for the \"MaxSources\" option: `1`.";

Chatbook::InvalidTaskPrompt = "\
Invalid value for the \"TaskPrompt\" option: `1`.";

Chatbook::InstructionsFunctionOutputFailure = "\
The instructions function `1` returned an invalid output: `2`.";

Chatbook::InstructionsFunctionLengthFailure = "\
The instructions function `1` returned a list of length `2` for `3` values.";

Chatbook::SnippetFunctionOutputFailure = "\
The snippet function `1` returned an invalid output: `2`.";

Chatbook::SnippetFunctionLengthFailure = "\
The snippet function `1` returned a list of length `2` for `3` values.";

(* ::**************************************************************************************************************:: *)
(* ::Section::Closed:: *)
(*$RelatedDocumentationSources*)
$RelatedDocumentationSources = Automatic;

(* ::**************************************************************************************************************:: *)
(* ::Section::Closed:: *)
(*RelatedDocumentation*)
RelatedDocumentation // beginDefinition;
RelatedDocumentation // Options = {
    "DownloadBatchSize" -> $snippetFetchBatchSize,
    "FilteredCount"     -> Automatic,
    "FilterResults"     -> Automatic,
    "LLMEvaluator"      -> Automatic,
    "MaxItems"          -> Automatic,
    "MaxSources"        -> $maxSelectedSources,
    "PromptHeader"      -> Automatic,
    "RerankMethod"      -> Automatic,
    "RerankPromptStyle" -> Automatic,
    "Sources"           :> $RelatedDocumentationSources,
    "TaskPrompt"        -> $taskPrompt
};

GeneralUtilities`SetUsage[ RelatedDocumentation, "\
RelatedDocumentation[\"string$\"] gives a list of documentation URIs that are semantically related to the \
conversational-style question specified by \"string$\".
RelatedDocumentation[All] gives the full list of available documentation URIs." ];

RelatedDocumentation[ ___ ] /; $noSemanticSearch := Failure[
    "SemanticSearchUnavailable",
    <|
        "MessageTemplate"   :> "SemanticSearch paclet is not available.",
        "MessageParameters" -> { }
    |>
];

RelatedDocumentation[ prompt_, opts: OptionsPattern[ ] ] :=
    catchMine @ RelatedDocumentation[ prompt, Automatic, opts ];

RelatedDocumentation[ prompt_, Automatic, opts: OptionsPattern[ ] ] :=
    catchMine @ RelatedDocumentation[ prompt, "URIs", opts ];

RelatedDocumentation[ prompt_, count: _Integer | UpTo[ _Integer ], opts: OptionsPattern[ ] ] :=
    RelatedDocumentation[ prompt, Automatic, count, opts ];

RelatedDocumentation[ prompt_, property_, opts: OptionsPattern[ ] ] :=
    catchMine @ RelatedDocumentation[
        prompt,
        property,
        getMaxItems[
            OptionValue @ MaxItems,
            getSources[ prompt, OptionValue[ "Sources" ], OptionValue[ "MaxSources" ] ]
        ],
        opts
    ];

RelatedDocumentation[ prompt_, Automatic, count_, opts: OptionsPattern[ ] ] :=
    RelatedDocumentation[ prompt, "URIs", count, opts ];

RelatedDocumentation[ prompt: $$prompt, "URIs", Automatic, opts: OptionsPattern[ ] ] := catchMine @ Enclose[
    (* TODO: filter results *)
    URL /@ ConfirmMatch[
        vectorDBSearch[ getSources[ prompt, OptionValue[ "Sources" ], OptionValue[ "MaxSources" ] ], prompt, "Values" ],
        { ___String },
        "Values"
    ],
    throwInternalFailure
];

RelatedDocumentation[ All, "URIs", Automatic, opts: OptionsPattern[ ] ] := catchMine @ Enclose[
    (* TODO: filter results *)
    URL /@ Union @ ConfirmMatch[
        vectorDBSearch[ getSources[ None, OptionValue[ "Sources" ], OptionValue[ "MaxSources" ] ], All ],
        { ___String },
        "Values"
    ],
    throwInternalFailure
];

RelatedDocumentation[ prompt: $$prompt, "Snippets", Automatic, opts: OptionsPattern[ ] ] := catchMine @ Enclose[
    ConfirmMatch[
        (* TODO: filter results *)
        Block[ { $snippetFetchBatchSize = OptionValue[ "DownloadBatchSize" ] },
            DeleteMissing @ makeDocSnippets @ vectorDBSearch[
                getSources[ prompt, OptionValue[ "Sources" ], OptionValue[ "MaxSources" ] ],
                prompt,
                "Results"
            ]
        ],
        { ___String },
        "Snippets"
    ],
    throwInternalFailure
];

RelatedDocumentation[ prompt_, property_, UpTo[ n_Integer ], opts: OptionsPattern[ ] ] :=
    catchMine @ RelatedDocumentation[ prompt, property, n, opts ];

RelatedDocumentation[ prompt_, property_, n_Integer, opts: OptionsPattern[ ] ] := catchMine @ Enclose[
    Take[ ConfirmBy[ RelatedDocumentation[ prompt, property, Automatic, opts ], ListQ ], UpTo @ n ],
    throwInternalFailure
];

RelatedDocumentation[
    prompt: $$prompt,
    property: "Results"|"Values"|"EmbeddingVector"|All,
    n_Integer,
    opts: OptionsPattern[ ]
] :=
    catchMine @ Enclose[
        (* TODO: filter results *)
        Block[ { $maxNeighbors = Max[ n * 5, 100 ] },
            Take[
                ConfirmBy[
                    vectorDBSearch[
                        LogChatTiming @ getSources[ prompt, OptionValue[ "Sources" ], OptionValue[ "MaxSources" ] ],
                        prompt,
                        property
                    ] // LogChatTiming[ "OuterVectorDBSearch" ],
                    ListQ,
                    "Results"
                ],
                UpTo @ n
            ]
        ],
        throwInternalFailure
    ];

RelatedDocumentation[ prompt_, property: "Index"|"Distance", n_Integer, opts: OptionsPattern[ ] ] :=
    catchMine @ Enclose[
        Lookup[
            Take[
                ConfirmMatch[
                    RelatedDocumentation[ prompt, "Results", n, opts ],
                    { KeyValuePattern[ property -> _ ]... },
                    "Results"
                ],
                UpTo @ n
            ],
            property
        ],
        throwInternalFailure
    ];

RelatedDocumentation[ prompt_, "Prompt", n_Integer, opts: OptionsPattern[ ] ] :=
    catchMine @ withChatState @ Block[
        {
            $rerankMethod = Replace[
                OptionValue[ "RerankMethod" ],
                $$unspecified :> $rerankMethod
            ],
            $bestDocumentationPromptMethod = Replace[
                OptionValue[ "RerankPromptStyle" ],
                $$unspecified :> $bestDocumentationPromptMethod
            ],
            $filteringLLMConfig = Replace[
                OptionValue[ "LLMEvaluator" ],
                $$unspecified :> $filteringLLMConfig
            ],
            $usePromptHeader = Replace[
                OptionValue[ "PromptHeader" ],
                $$unspecified :> $usePromptHeader
            ],
            $RelatedDocumentationSources = getSources[ prompt, OptionValue[ "Sources" ], OptionValue[ "MaxSources" ] ],
            $snippetFetchBatchSize = OptionValue[ "DownloadBatchSize" ],
            $taskPrompt = getTaskPrompt @ OptionValue[ "TaskPrompt" ]
        },
        relatedDocumentationPrompt[
            ensureChatMessages @ prompt,
            n,
            MatchQ[ OptionValue[ "FilterResults" ], Automatic|True ],
            Replace[ OptionValue[ "FilteredCount" ], Automatic -> Ceiling[ n / 5 ] ]
        ]
    ];

RelatedDocumentation[ args___ ] := catchMine @ throwFailure[
    "InvalidArguments",
    RelatedDocumentation,
    HoldForm @ RelatedDocumentation @ args
];

RelatedDocumentation // endDefinition;

(* ::**************************************************************************************************************:: *)
(* ::Subsection::Closed:: *)
(*getTaskPrompt*)
getTaskPrompt // beginDefinition;
getTaskPrompt[ prompt_String ] := prompt;
getTaskPrompt[ $$unspecified ] := $taskPrompt;
getTaskPrompt[ None ] := "";
getTaskPrompt[ other_ ] := throwFailure[ "InvalidTaskPrompt", other ];
getTaskPrompt // endDefinition;

(* ::**************************************************************************************************************:: *)
(* ::Subsection::Closed:: *)
(*getMaxItems*)
getMaxItems // beginDefinition;
getMaxItems[ $$unspecified, sources_List ] := Max[ $minUnfilteredItems, $unfilteredItemsPerSource * Length @ sources ];
getMaxItems[ Infinity, _ ] := 125;
getMaxItems[ n: $$size, _ ] := Ceiling @ n;
getMaxItems[ UpTo[ n_ ], sources_ ] := getMaxItems[ n, sources ];
getMaxItems // endDefinition;

(* ::**************************************************************************************************************:: *)
(* ::Subsection::Closed:: *)
(*getSources*)
getSources // beginDefinition;
getSources[ prompt_, names_List, max_ ] := toSource /@ Flatten @ names;
getSources[ prompt_, name_String, max_ ] := { toSource @ name };
getSources[ prompt_, All, max_ ] := toSource /@ $defaultSources;
getSources[ None, Automatic, max_Integer? NonNegative ] := toSource /@ Take[ $defaultSources, UpTo[ max ] ];
getSources[ prompt_, Automatic, max_Integer? NonNegative ] := LogChatTiming @ autoSelectSources[ prompt, max ];
getSources[ prompt_, source_, max_Integer? NonNegative ] := throwFailure[ "InvalidSources", source ];
getSources[ prompt_, source_, max_ ] := throwFailure[ "InvalidMaxSources", max ];
getSources // endDefinition;

(* ::**************************************************************************************************************:: *)
(* ::Subsubsection::Closed:: *)
(*autoSelectSources*)
autoSelectSources // beginDefinition;

autoSelectSources[ prompt_, max_ ] /; max >= Length @ $defaultSources :=
    toSource /@ $defaultSources;

autoSelectSources[ prompt_, max_Integer? NonNegative ] := Enclose[
    Module[ { values },
        values = ConfirmMatch[ vectorDBSearch[ "SourceSelector", prompt, "Values" ], { ___String }, "Values" ];
        $lastSelectedSources = ConfirmMatch[ toSource /@ Take[ values, UpTo[ max ] ], { ___String }, "Result" ]
    ],
    throwInternalFailure
];

autoSelectSources // endDefinition;

(* ::**************************************************************************************************************:: *)
(* ::Subsubsection::Closed:: *)
(*toSource*)
toSource // beginDefinition;
toSource[ name_String ] := Lookup[ $sourceAliases, name, name ];
toSource // endDefinition;

(* ::**************************************************************************************************************:: *)
(* ::Subsection::Closed:: *)
(*relatedDocumentationPrompt*)
relatedDocumentationPrompt // beginDefinition;

relatedDocumentationPrompt[ messages: $$chatMessages, count_, filter_, filterCount_ ] := Enclose[
    Catch @ Module[ { results, filtered, string },

        results = ConfirmMatch[
            RelatedDocumentation[ messages, "Results", count ],
            { ___Association },
            "Results"
        ] // LogChatTiming[ "RelatedDocumentationResults" ] // withApproximateProgress[ "CheckingDocumentation", 0.2 ];

        If[ results === { }, Throw[ "" ] ];

        results = Take[ DeleteDuplicatesBy[ results, Lookup[ "Value" ] ], UpTo[ count ] ];

        filtered = ConfirmMatch[
            filterSnippets[ messages, results, filter, filterCount ] // LogChatTiming[ "FilterSnippets" ],
            { ___String },
            "Filtered"
        ];

        string = StringTrim @ StringRiffle[ DeleteCases[ filtered, "" ], "\n\n======\n\n" ];

        If[ StringContainsQ[ string, StartOfLine~~"# WFR > " ], needsBasePrompt[ "FunctionRepositoryIntegration" ] ];

        If[ string === "",
            "",
            addExampleDataHint @ prependRelatedDocsHeader[ string, filter ]
        ]
    ],
    throwInternalFailure
];

relatedDocumentationPrompt // endDefinition;

(* ::**************************************************************************************************************:: *)
(* ::Subsubsection::Closed:: *)
(*addExampleDataHint*)
addExampleDataHint // beginDefinition;

addExampleDataHint[ string_String ] := Enclose[
    Catch @ Module[ { exampleDataFiles, hintText },

        exampleDataFiles = Union @ StringCases[
            string,
            "\"" ~~ path: Shortest[ "ExampleData/" ~~ Except[ "\"" ].. ] ~~ "\"" /; exampleDataFileQ @ path :> path
        ];

        If[ exampleDataFiles === { }, Throw @ string ];

        hintText = ConfirmBy[
            TemplateApply[
                $exampleDataHintTemplate,
                <|
                    "Files" -> StringRiffle[ "* \"" <> # <> "\"" & /@ exampleDataFiles, "\n" ],
                    "First" -> First @ exampleDataFiles
                |>
            ],
            StringQ,
            "HintText"
        ];

        needsBasePrompt[ "ExampleDataFiles" ];

        StringJoin[ string, "\n\n", hintText ]
    ],
    throwInternalFailure
];

addExampleDataHint // endDefinition;


$exampleDataHintTemplate = StringTemplate[ "\
<system-hint>
The \"ExampleData/\" directory is included in every Wolfram Language installation and is automatically on $Path, \
so paths like \"ExampleData/coneflower.jpg\" can be used immediately without any setup.

Available ExampleData files from the snippets above:
%%Files%%

You can use the following to find the list of all available ExampleData files:

```wl
FileNameTake /@ FileNames[All, DirectoryName[FindFile[\"%%First%%\"]]]
```
</system-hint>", Delimiters -> "%%" ];

(* ::**************************************************************************************************************:: *)
(* ::Subsubsection::Closed:: *)
(*exampleDataFileQ*)
exampleDataFileQ // beginDefinition;
exampleDataFileQ[ path_String ] := exampleDataFileQ[ path ] = StringQ @ Quiet @ FindFile @ path;
exampleDataFileQ // endDefinition;

(* ::**************************************************************************************************************:: *)
(* ::Subsubsection::Closed:: *)
(*prependRelatedDocsHeader*)
prependRelatedDocsHeader // beginDefinition;
prependRelatedDocsHeader[ string_String, _    ] /; ! TrueQ @ $usePromptHeader := string;
prependRelatedDocsHeader[ string_String, True ] := $relatedDocsStringFilteredHeader <> string;
prependRelatedDocsHeader[ string_String, _    ] := $relatedDocsStringUnfilteredHeader <> string;
prependRelatedDocsHeader // endDefinition;


$relatedDocsStringFilteredHeader =
"IMPORTANT: Here are some Wolfram documentation snippets that you should use to respond.\n\n======\n\n";

$relatedDocsStringUnfilteredHeader =
"Here are some Wolfram documentation snippets that you may find useful.\n\n======\n\n";

(* ::**************************************************************************************************************:: *)
(* ::Subsubsection::Closed:: *)
(*filterSnippets*)
filterSnippets // beginDefinition;


filterSnippets[ messages_, results_List, Except[ True ], filterCount_ ] := Enclose[
    ConfirmMatch[ makeDocSnippets @ results, { ___String }, "Snippets" ],
    throwInternalFailure
];


filterSnippets[
    messages_,
    results_List,
    True,
    filterCount_Integer? Positive
] /; $rerankMethod === None := Enclose[
    Catch @ Module[ { snippets },
        snippets = ConfirmMatch[ makeDocSnippets @ results, { ___String }, "Snippets" ];
        Take[ snippets, UpTo[ filterCount ] ]
    ],
    throwInternalFailure
];


filterSnippets[
    messages_,
    results_List,
    True,
    filterCount_Integer? Positive
] /; $rerankMethod === "rerank-english-v3.0" (* EXPERIMENTAL *) := Enclose[
    Catch @ Module[ { snippets, inserted, transcript, instructions, resp, respResults, idx, ranked },

        snippets = ConfirmMatch[ makeDocSnippets @ results, { ___String }, "Snippets" ];
        setProgressDisplay[ "ChoosingDocumentation" ];
        inserted = insertContextPrompt @ messages;
        transcript = ConfirmBy[ getSmallContextString @ inserted, StringQ, "Transcript" ];

        instructions = ConfirmBy[
            TemplateApply[ $documentationRerankPrompt, <| "TaskPrompt" -> $taskPrompt, "Transcript" -> transcript |> ],
            StringQ,
            "Prompt"
        ];

        resp = ServiceExecute[
            "Cohere",
            "RawRerank",
            {
                "model"     -> "rerank-english-v3.0",
                "query"     -> instructions,
                "documents" -> snippets
            }
        ];

        If[ FailureQ @ resp, throwTop @ resp ];

        respResults = ConfirmMatch[ resp[ "results" ], { __Association }, "Results" ];

        idx = ConfirmMatch[
            Select[ respResults, #[ "relevance_score" ] > 0.01 & ][[ All, "index" ]] + 1,
            { ___Integer },
            "Indices"
        ];

        ranked = ConfirmMatch[ snippets[[ idx ]], { ___String }, "Ranked" ];

        (* FIXME: need to add handler data here *)

        Take[ ranked, UpTo[ filterCount ] ]
    ],
    throwInternalFailure
];


filterSnippets[ messages_, results0_List, True, filterCount_Integer? Positive ] := Enclose[
    Catch @ Module[
        {
            results, inserted, transcript, xml, ids,
            instructions, response, uriToSnippet, uris, selected, pages
        },

        results = ConfirmMatch[ addInstructions @ addDocSnippets @ results0, { ___Association }, "Results" ];
        setProgressDisplay[ "ChoosingDocumentation" ];
        inserted = insertContextPrompt @ messages;
        transcript = ConfirmBy[ getSmallContextString @ inserted, StringQ, "Transcript" ];

        xml = ConfirmMatch[ DeleteDuplicates[ snippetXML /@ results ], { __String }, "XML" ];
        ids = DeleteDuplicates @ ConfirmMatch[ uriToSnippetID /@ results[[ All, "Value" ]], { ___String }, "IDs" ];
        instructions = ConfirmBy[
            TemplateApply[
                $bestDocumentationPrompt,
                <|
                    "TaskPrompt"    -> $taskPrompt,
                    "FilteredCount" -> filterCount,
                    "Snippets"      -> StringRiffle[ xml, "\n\n" ],
                    "Transcript"    -> transcript,
                    "SnippetIDs"    -> StringRiffle[ ids, "\n" ]
                |>
            ],
            StringQ,
            "Prompt"
        ];

        response = StringTrim @ ConfirmBy[
            LogChatTiming[
                setServiceCaller[
                    llmSynthesize[
                        instructions,
                        Replace[ $filteringLLMConfig, Automatic -> Verbatim @ Automatic, { 1 } ]
                    ],
                    "RelatedDocumentation"
                ],
                "WaitForFilterSnippetsTask"
            ] // withApproximateProgress[ 0.5 ],
            StringQ,
            "Response"
        ];

        If[ StringContainsQ[ response, "CasualChat" ], response = "" ];

        uriToSnippet = GroupBy[ results, Lookup[ "Value" ] -> Lookup[ "Snippet" ] ];
        uris = ConfirmMatch[ Keys @ uriToSnippet, { ___String }, "URIs" ];

        selected = ConfirmMatch[
            LogChatTiming @ selectSnippetsFromResponse[ response, uris ],
            { ___String },
            "Selected"
        ];

        pages = ConfirmMatch[
            DeleteDuplicates @ Flatten @ Lookup[ uriToSnippet, selected ],
            { ___String },
            "Pages"
        ];

        KeyValueMap[
            AddToSources,
            KeyTake[
                <| #Value -> #Snippet & /@ DeleteCases[ results, KeyValuePattern[ "Type" -> "Instructions" ] ] |>,
                selected
            ]
        ];

        addHandlerArguments[
            "RelatedDocumentation" -> <|
                "Results"      -> uris,
                "Filtered"     -> selected,
                "Response"     -> response,
                "Instructions" -> instructions
            |>
        ];

        pages
    ],
    throwInternalFailure
];


filterSnippets // endDefinition;



$bestDocumentationPromptLarge = StringTemplate[ "\
%%TaskPrompt%%

Each snippet is uniquely identified by a URI (always starts with 'paclet:' or 'https://*.wolframcloud.com').
You must also include the fragment appearing after the '#' in the URI.

Choose up to %%FilteredCount%% documentation snippets that would help answer the user's MOST RECENT message.

Respond with JSON in the following format:
{
	\"AssistantType\": assistantType,
	\"Snippets\": [
		{\"URI\": uri1, \"Score\": score1},
		{\"URI\": uri2, \"Score\": score2},
		...
	]
}

For \"AssistantType\", specify the type of assistant that should handle the user's message:
	\"Computational\": The user's message requires a computational response.
	\"Knowledge\": The user's message requires a knowledge-based response.
	\"Data\": The user's message requires a data, multimedia, or entity-based response.
	\"CasualChat\": The user's message is casual and could be answered by a non-specialist. For example, simple greetings or general questions.

Specify a score as any number from 1 to 5 for your chosen snippets using the following rubric:
	1: The snippet is completely irrelevant to the user's message or has no usefulness.
	2: The snippet is somewhat related, but the assistant could easily answer the user's message without it.
	3: The snippet is related and might help the assistant answer the user's message.
	4: The snippet is very relevant and would significantly help the assistant answer the user's message.
	5: It would be impossible for the assistant to answer the user's message correctly without this snippet.

Here is the chat transcript:

<transcript>
%%Transcript%%
</transcript>

Here are the available documentation snippets to choose from:

<snippets>
%%Snippets%%
</snippets>

Reminder: Choose up to %%FilteredCount%% documentation snippets that would help answer the user's MOST RECENT message.
You can (and should) skip snippets that are not relevant to the user's message or are redundant.
A snippet does not need to exactly answer the user's message in full in order to be relevant.
Respond only with the specified JSON and nothing else.
If there are no relevant pages, respond with [].
", Delimiters -> "%%" ];



$bestDocumentationPromptSmall = StringTemplate[ "\
%%TaskPrompt%%

On the first line of your response, write one of these assistant types:
	\"Computational\": The user's message requires a computational response.
	\"Knowledge\": The user's message requires a knowledge-based response.
	\"Data\": The user's message requires a data, multimedia, or entity-based response.
	\"CasualChat\": The user's message is casual and could be answered by a non-specialist. For example, simple greetings or general questions.

Then on each subsequent line, write a score (1-5) and id pair, separated by a space:
<score> <id>

Specify the score as any number from 1 to 5 for your chosen snippets using the following rubric:
	1: The snippet is completely irrelevant to the user's message or has no usefulness.
	2: The snippet is somewhat related, but the assistant could easily answer the user's message without it.
	3: The snippet is related and might help the assistant answer the user's message.
	4: The snippet is very relevant and would significantly help the assistant answer the user's message.
	5: It would be impossible for the assistant to answer the user's message correctly without this snippet.

<example>
Computational
4 Plus-3
3 ArithmeticFunctions-1
</example>

Here is the chat transcript:

<transcript>
%%Transcript%%
</transcript>

Available documentation snippets:

<snippets>
%%Snippets%%
</snippets>

Choose up to %%FilteredCount%% of the most relevant snippets. Skip irrelevant or redundant ones.
If there are multiple snippets that express the same idea, you should prefer the one that is easiest to understand.
If no relevant pages exist, only respond with the assistant type.
A snippet does not need to exactly answer the user's message in full in order to be relevant.
Respond only in the specified format and do not include any other text.

Reminder: These are the available snippet IDs:
%%SnippetIDs%%\
", Delimiters -> "%%" ];



$documentationRerankPrompt = StringTemplate[ "\
%%TaskPrompt%%

The snippet does not need to exactly answer the user's message if it can be easily generalized.
Prefer built-in system symbols over other resources.
Simpler is better.

Here is the chat transcript:

<transcript>
%%Transcript%%
</transcript>\
", Delimiters -> "%%" ];

(* ::**************************************************************************************************************:: *)
(* ::Subsubsection::Closed:: *)
(*selectSnippetsFromResponse*)
selectSnippetsFromResponse // beginDefinition;

selectSnippetsFromResponse[ response_String, uris_List ] /; $bestDocumentationPromptMethod === "JSON" := Enclose[
    Catch @ Module[ { jsonString, jsonData, selected },
        jsonString = ConfirmBy[ First[ StringCases[ response, Longest[ "{" ~~ __ ~~ "}" ], 1 ], None ], StringQ ];
        jsonData = ConfirmBy[ Quiet @ Developer`ReadRawJSONString @ jsonString, AssociationQ ];
        selected = ConfirmMatch[ Select[ jsonData[ "Snippets" ], #[ "Score" ] >= $rerankScoreThreshold & ], { __ } ];
        ConfirmMatch[
            Intersection[ Cases[ selected, KeyValuePattern[ "URI" -> uri_String ] :> StringTrim @ uri ], uris ],
            { __String }
        ]
    ],
    selectSnippetsFromString[ response, uris ] &
];

selectSnippetsFromResponse[ response_String, uris_List ] :=
    selectSnippetsFromResponseSmall[ response, uris, uriToSnippetID /@ uris ];

selectSnippetsFromResponse // endDefinition;

(* ::**************************************************************************************************************:: *)
(* ::Subsubsection::Closed:: *)
(*selectSnippetsFromResponseSmall*)
selectSnippetsFromResponseSmall // beginDefinition;

selectSnippetsFromResponseSmall[ response_String, uris_List, ids_List ] := Enclose[
    Catch @ Module[ { idPatt, scored, selected, selectedIDs, selectedURIs },

        If[ StringMatchQ[ StringTrim @ response, $$assistantTypeTag|"", IgnoreCase -> True ], Throw @ { } ];

        idPatt = ReverseSortBy[ ids, StringLength ];

        scored = ConfirmMatch[
            StringCases[
                response,
                StringExpression[
                    StartOfLine,
                    s: NumberString,
                    Whitespace,
                    Shortest[ Except[ "\n" ]... ],
                    id: idPatt,
                    Shortest[ Except[ "\n" ]... ],
                    WhitespaceCharacter...,
                    EndOfLine
                ] :> <| "Score" -> ToExpression @ s, "ID" -> snippetIDToURI @ id |>
            ],
            { __Association }
        ];

        ConfirmAssert[ AllTrue[ scored, NumberQ @ #[ "Score" ] & ], "ScoreCheck" ];

        selected = ReverseSortBy[
            ConfirmMatch[
                Select[ scored, #[ "Score" ] >= $rerankScoreThreshold & ],
                { ___Association }
            ],
            Lookup[ "Score" ]
        ];

        If[ selected === { }, Throw @ { } ];

        selectedIDs = ConfirmMatch[ Lookup[ selected, "ID" ], { ___String }, "SelectedIDs" ];
        selectedURIs = ConfirmMatch[ snippetIDToURI /@ selectedIDs, { ___String }, "SelectedURIs" ];
        ConfirmMatch[ DeleteDuplicates @ Cases[ selectedURIs, Alternatives @@ uris ], { ___String } ]
    ],
    snippetIDToURI /@ selectSnippetsFromString[ response, ids ] &
];

selectSnippetsFromResponseSmall // endDefinition;

(* ::**************************************************************************************************************:: *)
(* ::Subsubsection::Closed:: *)
(*scoreSnippetLine*)
scoreSnippetLine // beginDefinition;

scoreSnippetLine[ $$assistantTypeTag ] :=
    Nothing;

scoreSnippetLine[ line_String ] /; StringMatchQ[ StringTrim @ line, $$assistantTypeTag, IgnoreCase -> True ] :=
    Nothing;

scoreSnippetLine[ line_String ] := Enclose[
    Module[ { scoreString, id, score },
        { scoreString, id } = ConfirmMatch[ StringSplit[ line, Whitespace ], { _String, _String }, "Split" ];
        score = ToExpression @ ConfirmBy[ scoreString, StringMatchQ @ NumberString, "Score" ];
        <| "Score" -> score, "ID" -> id |>
    ],
    $Failed &
];

scoreSnippetLine // endDefinition;

(* ::**************************************************************************************************************:: *)
(* ::Subsubsection::Closed:: *)
(*selectSnippetsFromString*)
selectSnippetsFromString // beginDefinition;
selectSnippetsFromString[ response_String, ids: { ___String } ] := DeleteDuplicates @ StringCases[ response, ids ];
selectSnippetsFromString // endDefinition;

(* ::**************************************************************************************************************:: *)
(* ::Subsubsection::Closed:: *)
(*snippetXML*)
snippetXML // beginDefinition;

snippetXML[ KeyValuePattern @ { "Type" -> "Instructions", "Snippet" -> instructions_String } ] :=
    "<info>\n" <> instructions <> "\n</info>";

snippetXML[ KeyValuePattern[ "Snippet" -> snippet_String ] ] :=
    snippetXML @ snippet;

snippetXML[ snippet_String ] :=
    snippetXML[ snippet, $bestDocumentationPromptMethod ];

snippetXML[ snippet_String, "JSON" ] :=
    "<snippet>\n"<>snippet<>"\n</snippet>";

snippetXML[ snippet_String, "Small" ] := snippetXML[ snippet, "Small" ] = Enclose[
    StringReplace[
        snippet,
        StartOfString ~~ header: Except[ "\n" ].. ~~ "\n" ~~ uri: Except[ "\n" ].. ~~ "\n" ~~ rest__ ~~ EndOfString :>
            StringJoin[
                "<snippet id='", ConfirmBy[ uriToSnippetID @ uri, StringQ, "ID" ], "'>\n",
                header, "\n",
                rest, "\n</snippet>"
            ]
    ],
    throwInternalFailure
];

snippetXML[ snippet_String, other_ ] :=
    snippetXML[ snippet, "Small" ];

snippetXML // endDefinition;

(* ::**************************************************************************************************************:: *)
(* ::Subsubsection::Closed:: *)
(*uriToSnippetID*)
uriToSnippetID // beginDefinition;

uriToSnippetID[ URL[ uri_String ] ] :=
    uriToSnippetID @ uri;

uriToSnippetID[ uri_String ] /; StringStartsQ[ uri, "https://www.wolframalpha.com/input?i=" ] := Enclose[
    Module[ { base, counter, id },
        base = "WA";
        counter = ConfirmBy[ getSnippetIDCounter[ uri, base ], IntegerQ, "Counter" ];
        id = base <> "-" <> ToString @ counter;
        snippetIDToURI[ id ] = uri;
        uriToSnippetID[ uri ] = id
    ],
    throwInternalFailure
];

uriToSnippetID[ uri_String ] := Enclose[
    Module[ { split, base, counter, id },
        split = Last @ ConfirmMatch[ StringSplit[ uri, "/" ], { __String }, "Split" ];
        base = First @ StringSplit[ split, "#" ];
        counter = ConfirmBy[ getSnippetIDCounter[ uri, base ], IntegerQ, "Counter" ];
        id = base <> "-" <> ToString @ counter;
        snippetIDToURI[ id ] = uri;
        uriToSnippetID[ uri ] = id
    ],
    throwInternalFailure
];

uriToSnippetID // endDefinition;

(* ::**************************************************************************************************************:: *)
(* ::Subsubsection::Closed:: *)
(*snippetIDToURI*)
snippetIDToURI // beginDefinition;
(* This is defined for individual ids during evaluation of uriToSnippetID. *)
snippetIDToURI[ id_String ] := id;
snippetIDToURI // endDefinition;

(* ::**************************************************************************************************************:: *)
(* ::Subsubsection::Closed:: *)
(*getSnippetIDCounter*)
getSnippetIDCounter // beginDefinition;

getSnippetIDCounter[ uri_String ] :=
    getSnippetIDCounter[ uri, First @ StringSplit[ Last @ StringSplit[ uri, "/" ], "#" ] ];

getSnippetIDCounter[ uri_String, base_String ] := getSnippetIDCounter[ uri, base ] =
    If[ IntegerQ @ $snippetIDCounters[ base ],
        ++$snippetIDCounters[ base ],
        $snippetIDCounters[ base ] = 1
    ];

getSnippetIDCounter // endDefinition;

$snippetIDCounters = <| |>;

(* ::**************************************************************************************************************:: *)
(* ::Section::Closed:: *)
(*Documentation Snippets*)
$documentationSnippets = <| |>;

(* ::**************************************************************************************************************:: *)
(* ::Subsection::Closed:: *)
(*addInstructions*)
addInstructions // beginDefinition;

addInstructions[ results: { ___Association } ] := Enclose[
    Module[ { withOrdering, grouped, withInstructions, sorted },

        withOrdering = MapIndexed[ <| "Position" -> First[ #2 ], #1 |> &, results ];
        grouped      = GroupBy[ withOrdering, Lookup[ "Instructions" ] ];

        withInstructions = ConfirmMatch[
            Flatten @ KeyValueMap[ applyInstructionsFunction, grouped ],
            { ___Association },
            "WithInstructions"
        ];

        sorted = ConfirmMatch[ SortBy[ withInstructions, Lookup[ "Position" ] ], { ___Association }, "Sorted" ];

        ConfirmMatch[ addSpecialInstructions @ sorted, { ___Association }, "Result" ]
    ],
    throwInternalFailure
];

addInstructions // endDefinition;

(* ::**************************************************************************************************************:: *)
(* ::Subsubsection::Closed:: *)
(*addSpecialInstructions*)
addSpecialInstructions // beginDefinition;

addSpecialInstructions[ sorted_List ] := Enclose[
    Catch @ Module[ { as, entityInstructions },
        as = ConfirmMatch[ SelectFirst[ sorted, addBasicEntityInstructionsQ ], _Association|_Missing, "Entity" ];
        If[ MissingQ @ as, Throw @ sorted ];
        entityInstructions = ConfirmBy[ getNamedSnippet[ "BasicEntityUsage" ], StringQ, "EntityInstructions" ];
        Prepend[ sorted, <| as, "Position" -> 0, "Snippet" -> entityInstructions, "Type" -> "Instructions" |> ]
    ],
    throwInternalFailure
];

addSpecialInstructions // endDefinition;

(* ::**************************************************************************************************************:: *)
(* ::Subsubsection::Closed:: *)
(*addBasicEntityInstructionsQ*)
addBasicEntityInstructionsQ // beginDefinition;

addBasicEntityInstructionsQ[ KeyValuePattern[ "Snippet" -> s_String ] ] :=
    StringContainsQ[ s, "Entity"|"\[FreeformPrompt]"|"\\\[FreeformPrompt]" ];

addBasicEntityInstructionsQ // endDefinition;

(* ::**************************************************************************************************************:: *)
(* ::Subsubsection::Closed:: *)
(*applyInstructionsFunction*)
applyInstructionsFunction // beginDefinition;

applyInstructionsFunction[ f_, { } ] := { };

applyInstructionsFunction[ None|$$unspecified, data: { ___Association } ] := data;

applyInstructionsFunction[ URL[ uri_String ], data: { ___Association } ] :=
    applyInstructionsFunction[ getSnippets @ uri, data ];

applyInstructionsFunction[ instructions_List, data: { ___Association } ] :=
    Flatten[ applyInstructionsFunction[ #, data ] & /@ Flatten @ instructions ];

applyInstructionsFunction[ instructions_String, data: { ___Association } ] :=
    applyInstructionsFunction[ Map[ instructions & ], data ];

applyInstructionsFunction[ f_, data: { ___Association } ] := Enclose[
    Module[ { values, instructions, instructionsLen, valuesLen, threaded },

        values          = ConfirmMatch[ Lookup[ data, "Value" ], { ___String }, "Values" ];
        instructions    = f @ values;
        instructionsLen = Length @ instructions;
        valuesLen       = Length @ values;

        If[ ! MatchQ[ instructions, { (_String | { ___String } | None)... } ],
            throwFailure[ "InstructionsFunctionOutputFailure", f, instructions ]
        ];
        If[ instructionsLen =!= valuesLen,
            throwFailure[ "InstructionsFunctionLengthFailure", f, instructionsLen, valuesLen ]
        ];

        threaded = ConfirmBy[
            Association /@ Transpose @ { data, Thread[ "Instructions" -> instructions ] },
            AllTrue @ AssociationQ,
            "Threaded"
        ];

        ConfirmMatch[ expandInstructionPairs @ threaded, { ___Association }, "Expanded" ]

    ] // LogChatTiming @ { "ApplyInstructionsFunction", f },
    throwInternalFailure
];

applyInstructionsFunction // endDefinition;

(* ::**************************************************************************************************************:: *)
(* ::Subsubsection::Closed:: *)
(*expandInstructionPairs*)
expandInstructionPairs // beginDefinition;

expandInstructionPairs[ results_List ] :=
    Flatten[ expandInstructionPairs /@ results ];

expandInstructionPairs[ data: KeyValuePattern[ "Instructions" -> None ] ] :=
    data;

expandInstructionPairs[ data: KeyValuePattern[ "Instructions" -> instructions0_ ] ] :=
    Module[ { offset, position, instructions, instData },
        offset = If[ MatchQ[ data[ "InstructionsPosition" ], Before ], -0.5, 0.5 ];
        position = Lookup[ data, "Position", 0 ] + offset;
        instructions = Select[ Flatten @ { instructions0 }, StringQ ];
        instData = <| data, "Type" -> "Instructions", "Snippet" -> #, "Position" -> position |> & /@ instructions;
        SortBy[ Flatten @ { data, instData }, Lookup[ "Position" ] ]
    ];

expandInstructionPairs // endDefinition;

(* ::**************************************************************************************************************:: *)
(* ::Subsection::Closed:: *)
(*addDocSnippets*)
addDocSnippets // beginDefinition;

addDocSnippets[ results: { ___Association } ] := Enclose[
    Module[ { withOrdering, grouped, withSnippets, sorted },

        withOrdering = MapIndexed[ <| "Position" -> First[ #2 ], #1 |> &, results ];
        grouped      = GroupBy[ withOrdering, Lookup[ "SnippetFunction" ] ];

        withSnippets = ConfirmMatch[
            Flatten @ KeyValueMap[ applySnippetFunction, grouped ],
            { ___Association },
            "WithSnippets"
        ];

        sorted = ConfirmMatch[ SortBy[ withSnippets, Lookup[ "Position" ] ], { ___Association }, "Sorted" ];

        ConfirmAssert[ Length @ sorted === Length @ results, "LengthCheck" ];

        sorted
    ],
    throwInternalFailure
];

addDocSnippets // endDefinition;

(* ::**************************************************************************************************************:: *)
(* ::Subsubsection::Closed:: *)
(*applySnippetFunction*)
applySnippetFunction // beginDefinition;

applySnippetFunction[ f_, { } ] := { };

applySnippetFunction[ f_, data: { ___Association } ] := Enclose[
    Module[ { values, snippets, snippetLen, valuesLen, cleaned },

        values     = ConfirmMatch[ Lookup[ data, "Value" ], { ___String }, "Values" ];
        snippets   = f @ values;
        snippetLen = Length @ snippets;
        valuesLen  = Length @ values;

        If[ ! MatchQ[ snippets, { ___String } ], throwFailure[ "SnippetFunctionOutputFailure", f, snippets ] ];
        If[ snippetLen =!= valuesLen, throwFailure[ "SnippetFunctionLengthFailure", f, snippetLen, valuesLen ] ];

        cleaned = ConfirmMatch[ cleanSnippets @ snippets, { ___String }, "Cleaned" ];

        ConfirmBy[
            Association /@ Transpose @ { data, Thread[ "Snippet" -> cleaned ] },
            AllTrue @ AssociationQ,
            "Result"
        ]
    ] // LogChatTiming @ { "ApplySnippetFunction", f },
    throwInternalFailure
];

applySnippetFunction // endDefinition;

(* ::**************************************************************************************************************:: *)
(* ::Subsubsection::Closed:: *)
(*cleanSnippets*)
cleanSnippets // beginDefinition;

cleanSnippets[ snippets: _String | { ___String } ] := StringReplace[
    snippets,
    {
        md: Shortest[ "\\!\\(\\*MarkdownImageBox[\"![" ~~ __ ~~ "](" ~~ uri__ ~~ ")\"]\\)" ] :>
            If[ validExpressionURIQ @ uri,
                md,
                "<image removed>"
            ]
        ,
        md: Shortest[ "![cell image](" ~~ uri__ ~~ ")" ] :>
            If[ validExpressionURIQ @ uri,
                md,
                "<image removed>"
            ]
    }
];

cleanSnippets // endDefinition;

(* ::**************************************************************************************************************:: *)
(* ::Subsection::Closed:: *)
(*makeDocSnippets*)
makeDocSnippets // beginDefinition;

makeDocSnippets[ results: { ___Association } ] := Enclose[
    Module[ { sorted, snippets },
        sorted   = ConfirmMatch[ addDocSnippets @ results, { ___Association }, "Sorted" ];
        snippets = ConfirmMatch[ Lookup[ sorted, "Snippet" ], { ___String }, "Snippets" ];
        ConfirmAssert[ Length @ snippets === Length @ results, "LengthCheck" ];
        DeleteDuplicates @ snippets
    ],
    throwInternalFailure
];

makeDocSnippets // endDefinition;

(* ::**************************************************************************************************************:: *)
(* ::Subsection::Closed:: *)
(*getSnippets*)
getSnippets // beginDefinition;

getSnippets[ { } ] := { };

getSnippets[ uris: { ___String } ] := Enclose[
    Module[ { grouped, snippetGroups, snippets },
        grouped = GroupBy[ uris, streamableSnippetType ];
        ConfirmAssert[ ContainsOnly[ Keys @ grouped, $streamableSnippetTypes ], "TypeCheck" ];
        snippetGroups = Association @ KeyValueMap[ #1 -> getStreamSnippets[ #1, #2 ] &, grouped ];

        snippets = ConfirmBy[
            Association @ Values @ Merge[ { grouped, snippetGroups }, Apply @ AssociationThread ],
            AssociationQ,
            "Snippets"
        ];

        ConfirmMatch[ Lookup[ snippets, uris ], { ___String }, "Result" ]
    ],
    throwInternalFailure
];

getSnippets[ uri_String ] :=
    First @ getSnippets @ { uri };

getSnippets // endDefinition;

(* ::**************************************************************************************************************:: *)
(* ::Section::Closed:: *)
(*InstallDocumentationResources*)
InstallDocumentationResources // beginDefinition;
InstallDocumentationResources[ ] := catchMine[ $snippetDownloadDeclined = False; installDocumentationResources[ ] ];
InstallDocumentationResources // endExportedDefinition;

(* ::**************************************************************************************************************:: *)
(* ::Subsection::Closed:: *)
(*installDocumentationResources*)
installDocumentationResources // beginDefinition;

installDocumentationResources[ ] := Enclose[
    Module[ { dir },
        dir = ConfirmBy[ getStreamableSnippetsDir[ ], streamableSnippetsDirectoryQ, "Location" ];
        Success[ "DocumentationResourcesInstalled", <| "Location" -> dir |> ]
    ],
    throwInternalFailure
];

installDocumentationResources // endDefinition;

(* ::**************************************************************************************************************:: *)
(* ::Subsubsection::Closed:: *)
(*streamableSnippetType*)
streamableSnippetType // beginDefinition;
streamableSnippetType[ uri_String ] /; StringStartsQ[ uri, "paclet:" ] := "Documentation";
streamableSnippetType[ uri_String ] := "ResourceSystem";
streamableSnippetType // endDefinition;

(* ::**************************************************************************************************************:: *)
(* ::Section::Closed:: *)
(*Streamable Snippets*)
$streamableSnippetIndexCache = <| |>;

(* ::**************************************************************************************************************:: *)
(* ::Subsection::Closed:: *)
(*Paths*)
$streamableSnippetsDir := getStreamableSnippetsDir[ ];

$pacletStreamableSnippetsDirectory :=
    FileNameJoin @ { $thisPaclet[ "Location" ], "Assets/Snippets/Streamable" };

$localStreamableSnippetsDirectory :=
    ChatbookFilesDirectory @ { "DocumentationSnippets", "Streamable", $versionString };

$cloudStreamableSnippetsDirectory :=
    PacletObject[ "Wolfram/NotebookAssistantCloudResources" ][ "AssetLocation", "Snippets" ];

(* ::**************************************************************************************************************:: *)
(* ::Subsection::Closed:: *)
(*getStreamableSnippetsDir*)
getStreamableSnippetsDir // beginDefinition;

getStreamableSnippetsDir[ ] := Enclose[
    Module[ { sources, dir },
        sources = {
            $pacletStreamableSnippetsDirectory,
            If[ $CloudEvaluation, $cloudStreamableSnippetsDirectory, Nothing ],
            $localStreamableSnippetsDirectory
        };

        dir = SelectFirst[
            sources,
            streamableSnippetsDirectoryQ,
            ConfirmBy[ downloadStreamableSnippets[ ], streamableSnippetsDirectoryQ, "Downloaded" ]
        ];

        $streamableSnippetsDir = dir
    ],
    throwInternalFailure
];

getStreamableSnippetsDir // endDefinition;

(* ::**************************************************************************************************************:: *)
(* ::Subsubsection::Closed:: *)
(*streamableSnippetsDirectoryQ*)
streamableSnippetsDirectoryQ // beginDefinition;

streamableSnippetsDirectoryQ[ dir_String ] := TrueQ @ And[
    DirectoryQ @ dir,
    streamableSnippetsDirectoryQ @ FileNames[ Keys @ $streamableSnippetVersions, dir ]
];

streamableSnippetsDirectoryQ[ dirs: { ___String } ] := TrueQ @ And[
    Length @ dirs === Length @ $streamableSnippetVersions,
    AllTrue[ dirs, streamableSnippetsDirectoryQ0 ]
];

streamableSnippetsDirectoryQ[ None ] := False;

streamableSnippetsDirectoryQ // endDefinition;


streamableSnippetsDirectoryQ0 // beginDefinition;

streamableSnippetsDirectoryQ0[ dir_? DirectoryQ ] :=
    AssociationQ @ Quiet @ catchAlways @ getStreamableSnippetsMetadata @ File @ dir;

streamableSnippetsDirectoryQ0[ _ ] := False;

streamableSnippetsDirectoryQ0 // endDefinition;

(* ::**************************************************************************************************************:: *)
(* ::Subsubsection::Closed:: *)
(*getStreamableSnippetsMetadata*)
getStreamableSnippetsMetadata // beginDefinition;

getStreamableSnippetsMetadata[ name_String ] :=
    With[ { cached = $streamableSnippetIndexCache[ name ] },
        cached /; AssociationQ @ cached
    ];

getStreamableSnippetsMetadata[ name_String ] :=
    getStreamableSnippetsMetadata @ File @ FileNameJoin @ { $streamableSnippetsDir, name };

getStreamableSnippetsMetadata[ File[ dir_String ] ] := Enclose[
    Quiet @ Module[ { metaFile, indexFile, payloadFile, metadata, name, version, count, size, index, data },

        metaFile    = ConfirmBy[ FileNameJoin @ { dir, "Metadata.wxf"  }, FileExistsQ, "MetadataFile" ];
        indexFile   = ConfirmBy[ FileNameJoin @ { dir, "Index.wxf"     }, FileExistsQ, "IndexFile"    ];
        payloadFile = ConfirmBy[ FileNameJoin @ { dir, "Snippets.wxfl" }, FileExistsQ, "PayloadFile"  ];

        metadata    = ConfirmBy[ Developer`ReadWXFFile @ metaFile, AssociationQ, "Metadata" ];

        name        = ConfirmBy[ metadata[ "Name"        ], StringQ , "Name"    ];
        version     = ConfirmBy[ metadata[ "Version"     ], StringQ , "Version" ];
        count       = ConfirmBy[ metadata[ "Count"       ], IntegerQ, "Count"   ];
        size        = ConfirmBy[ metadata[ "PayloadSize" ], IntegerQ, "Size"    ];

        ConfirmAssert[ $streamableSnippetVersions[ name ] === version, "VersionCheck" ];

        index = ConfirmBy[ Developer`ReadWXFFile @ indexFile, AssociationQ, "Index" ];

        ConfirmAssert[ Length @ index === count, "IndexLengthCheck" ];
        ConfirmAssert[ FileByteCount @ payloadFile === size, "PayloadSizeCheck" ];

        data = <| metadata, "Index" -> index, "PayloadFile" -> payloadFile |>;

        (* Cache for later use *)
        $streamableSnippetIndexCache[ name ] = data;

        data
    ],
    throwInternalFailure
];

getStreamableSnippetsMetadata // endDefinition;

(* ::**************************************************************************************************************:: *)
(* ::Subsubsection::Closed:: *)
(*downloadStreamableSnippets*)
downloadStreamableSnippets // beginDefinition;

downloadStreamableSnippets[ ] /; TrueQ @ $snippetDownloadDeclined :=
    Quiet @ throwFailure[ "SnippetDownloadDeclined" ];

downloadStreamableSnippets[ ] := Enclose[
    Module[ { dir, lock },
        dir  = ConfirmBy[ GeneralUtilities`EnsureDirectory @ $localStreamableSnippetsDirectory, DirectoryQ, "Directory" ];
        lock = FileNameJoin @ { dir, "download.lock" };
        WithLock[ File @ lock, downloadStreamableSnippetsLocked @ dir, PersistenceTime -> $snippetLockPersistence ]
    ] // LogChatTiming[ "DownloadStreamableSnippets" ],
    throwInternalFailure
];

downloadStreamableSnippets[ dir_String, name_String ] /; TrueQ @ $snippetDownloadDeclined :=
    Missing[ "Cancelled" ];

downloadStreamableSnippets[ dir_String, name_String ] :=
    downloadStreamableSnippets[ dir, name, 1, None ];

downloadStreamableSnippets[ dir_String, name_String, attempt_Integer, rate_ ] /; attempt > $maxDownloadAttempts :=
    Failure[ "SnippetDownloadFailed", <| "Name" -> name |> ];

downloadStreamableSnippets[ dir_String, name_String, attempt_Integer, rate_ ] := Enclose[
    Catch @ Module[ { retry, ver, url, tmp, start, response, newRate, size },

        If[ attempt > 1,
            If[ ! confirmDownloadRetry[ trStringTemplate[ "DownloadLabelDocumentation" ][ name ], $streamableSnippetSizes @ name, rate ],
                $snippetDownloadDeclined = True;
                Throw @ Missing[ "Cancelled" ]
            ];
            Pause[ attempt - 1 ]
        ];

        tmp = FileNameJoin @ { $TemporaryDirectory, name <> "-" <> CreateUUID[ ] <> ".zip" };
        retry = Function[
            Quiet @ DeleteFile @ tmp;
            Throw @ downloadStreamableSnippets[ dir, name, attempt + 1, newRate ]
        ];

        ver = ConfirmBy[ StringReplace[ $streamableSnippetVersions @ name, "." -> "-" ], StringQ, "Version" ];
        url = ConfirmBy[ URLBuild @ { $streamableSnippetBaseURL, name, ver<>".zip" }, StringQ, "URL" ];

        start    = AbsoluteTime[ ];
        response = Quiet @ URLDownload[ url, tmp, { "File", "StatusCode" } ];
        size     = Quiet @ FileByteCount @ tmp;
        newRate  = If[ IntegerQ @ size && size > 0, size / Max[ AbsoluteTime[ ] - start, 0.001 ], rate ];

        If[ ! MatchQ[ response, KeyValuePattern[ "StatusCode" -> 200 ] ], retry[ ] ];
        If[ ! validSnippetArchiveQ[ name, tmp ], retry[ ] ];

        WithCleanup[
            Replace[ installSnippetArchive[ dir, name, tmp ], Except[ _String? DirectoryQ ] :> retry[ ] ],
            Quiet @ DeleteFile @ tmp
        ]
    ],
    throwInternalFailure
];

downloadStreamableSnippets // endDefinition;

(* ::**************************************************************************************************************:: *)
(* ::Subsubsection::Closed:: *)
(*downloadStreamableSnippetsLocked*)
downloadStreamableSnippetsLocked // beginDefinition;

downloadStreamableSnippetsLocked[ dir_String ] := Enclose[
    Catch @ Module[ { partial, queue, damaged, failed },

        Scan[ restoreSnippetBackup[ dir, # ] &, $streamableSnippetTypes ];

        partial = Select[ $streamableSnippetTypes, staleSnippetArtifacts[ dir, # ] =!= { } & ];
        Quiet[ DeleteDirectory[ #, DeleteContents -> True ] & /@ Flatten[ staleSnippetArtifacts[ dir, # ] & /@ $streamableSnippetTypes ] ];

        (* Another kernel may have finished installing while we were waiting for the lock: *)
        queue = Select[ $streamableSnippetTypes, ! streamableSnippetsDirectoryQ0 @ FileNameJoin @ { dir, # } & ];
        If[ queue === { }, Throw @ dir ];

        damaged = Select[ queue, MemberQ[ partial, # ] || snippetsDamagedQ[ dir, # ] & ];

        If[ damaged =!= { } && TrueQ @ $promptRedownload,
            If[ ! confirmRedownload[ "DownloadTypeDocumentation", damaged, Total @ Lookup[ $streamableSnippetSizes, damaged, 0 ] ],
                $snippetDownloadDeclined = True;
                throwFailure[ "SnippetDownloadDeclined" ]
            ]
        ];

        Scan[ (Quiet @ $streamableSnippetIndexCache[ # ] =.) &, queue ];

        failed = withApproximateProgress[
            Select[
                queue,
                If[ TrueQ @ $snippetDownloadDeclined, True, ! StringQ @ downloadStreamableSnippets[ dir, # ] ] &
            ],
            "DownloadingDocumentation",
            0.5
        ];

        Which[
            failed === { }, ConfirmBy[ dir, streamableSnippetsDirectoryQ, "Result" ],
            TrueQ @ $snippetDownloadDeclined, throwFailure[ "SnippetDownloadDeclined" ],
            True, throwFailure[ "SnippetDownloadFailed", StringRiffle[ failed, ", " ] ]
        ]
    ],
    throwInternalFailure
];

downloadStreamableSnippetsLocked // endDefinition;

(* ::**************************************************************************************************************:: *)
(* ::Subsubsection::Closed:: *)
(*staleSnippetArtifacts*)
staleSnippetArtifacts // beginDefinition;

staleSnippetArtifacts[ dir_String, name_String ] := Select[
    FileNames[ { name <> ".staging", name <> ".old-*" }, dir ],
    With[ { date = Quiet @ FileDate[ #, "Modification" ] },
        ! DateObjectQ @ date || AbsoluteTime[ ] - AbsoluteTime @ date > 120
    ] &
];

staleSnippetArtifacts // endDefinition;

(* ::**************************************************************************************************************:: *)
(* ::Subsubsection::Closed:: *)
(*restoreSnippetBackup*)
restoreSnippetBackup // beginDefinition;

restoreSnippetBackup[ root_String, name_String ] :=
    With[ { target = FileNameJoin @ { root, name } },
        If[ ! DirectoryQ @ target,
            With[ { backups = FileNames[ name <> ".old-*", root ] },
                If[ backups =!= { }, Quiet @ Check[ RenameDirectory[ Last @ Sort @ backups, target ], $Failed ] ]
            ]
        ]
    ];

restoreSnippetBackup // endDefinition;

(* ::**************************************************************************************************************:: *)
(* ::Subsubsection::Closed:: *)
(*snippetsDamagedQ*)
(* An existing install for the current version that fails validation (as opposed to a fresh install or an update): *)
snippetsDamagedQ // beginDefinition;

snippetsDamagedQ[ root_String, name_String ] :=
    With[ { dir = FileNameJoin @ { root, name } },
        TrueQ @ And[
            DirectoryQ @ dir,
            ! streamableSnippetsDirectoryQ0 @ dir,
            MatchQ[
                Quiet @ Developer`ReadWXFFile @ FileNameJoin @ { dir, "Metadata.wxf" },
                Except[ KeyValuePattern[ "Version" -> v_String /; v =!= $streamableSnippetVersions @ name ] ]
            ]
        ]
    ];

snippetsDamagedQ // endDefinition;

(* ::**************************************************************************************************************:: *)
(* ::Subsubsection::Closed:: *)
(*validSnippetArchiveQ*)
validSnippetArchiveQ // beginDefinition;

validSnippetArchiveQ[ name_String, file_String ] := TrueQ @ And[
    FileExistsQ @ file,
    With[ { size = Lookup[ $streamableSnippetSizes, name ], actual = FileByteCount @ file },
        IntegerQ @ size && actual === size
    ],
    With[ { hash = Lookup[ $streamableSnippetHashes, name ] },
        StringQ @ hash && Quiet @ FileHash[ file, "SHA256", All, "HexString" ] === hash
    ]
];

validSnippetArchiveQ // endDefinition;

(* ::**************************************************************************************************************:: *)
(* ::Subsubsection::Closed:: *)
(*installSnippetArchive*)
(* Extract into a staging directory, validate, then swap into place: *)
installSnippetArchive // beginDefinition;

installSnippetArchive[ dir_String, name_String, zip_String ] :=
    With[ { staging = FileNameJoin @ { dir, name <> ".staging" } },
        Replace[
            installSnippetArchive0[ dir, name, zip, staging ],
            failure_Failure :> (Quiet @ DeleteDirectory[ staging, DeleteContents -> True ]; failure)
        ]
    ];

installSnippetArchive // endDefinition;


installSnippetArchive0 // beginDefinition;

installSnippetArchive0[ dir_String, name_String, zip_String, staging_String ] := Enclose[
    Module[ { target, old, installed },
        target = FileNameJoin @ { dir, name };
        Quiet @ DeleteDirectory[ staging, DeleteContents -> True ];
        ConfirmBy[ CreateDirectory @ staging, DirectoryQ, "Staging" ];
        ConfirmMatch[ Quiet @ ExtractArchive[ zip, staging, OverwriteTarget -> True ], { __String }, "Extracted" ];
        ConfirmAssert[ streamableSnippetsDirectoryQ0 @ staging, "Validate" ];
        Quiet @ $streamableSnippetIndexCache[ name ] =.;

        If[ DirectoryQ @ target,
            old = target <> ".old-" <> CreateUUID[ ];
            ConfirmBy[ RenameDirectory[ target, old ], DirectoryQ, "MoveOld" ]
        ];

        installed = Quiet @ Check[ RenameDirectory[ staging, target ], $Failed ];
        If[ ! DirectoryQ @ installed,
            If[ StringQ @ old && DirectoryQ @ old && ! DirectoryQ @ target,
                Quiet @ Check[ RenameDirectory[ old, target ], $Failed ]
            ];
            ConfirmBy[ installed, DirectoryQ, "Install" ]
        ];

        If[ StringQ @ old && DirectoryQ @ old, Quiet @ DeleteDirectory[ old, DeleteContents -> True ] ];
        target
    ],
    Function[ failure, Failure[ "SnippetInstallFailed", <| "Name" -> name, "Reason" -> failure |> ] ]
];

installSnippetArchive0 // endDefinition;

(* ::**************************************************************************************************************:: *)
(* ::Subsection::Closed:: *)
(*getStreamSnippets*)
getStreamSnippets // beginDefinition;

getStreamSnippets[ name_String ] :=
    getStreamSnippets[ name, # ] &;

getStreamSnippets[ name_String, key_String ] :=
    First @ getStreamSnippets[ name, { key } ];

getStreamSnippets[ name_String, { } ] :=
    { };

getStreamSnippets[ name_String, keys: { __String } ] := Enclose[
    Module[ { file, keyGroups, stream, data, lookup, strings },

        file = ConfirmBy[ FileNameJoin @ { $streamableSnippetsDir, name, "Snippets.wxfl" }, FileExistsQ, "File" ];
        keyGroups = GroupBy[ keys, StringDelete[ #1, "#" ~~ ___ ~~ EndOfString ] & ];

        WithCleanup[
            stream = ConfirmMatch[ OpenRead[ file, BinaryFormat -> True ], _InputStream, "Stream" ],
            data = Association @ KeyValueMap[ getStreamSnippets0[ stream, name, #1, #2 ] &, keyGroups ],
            Quiet @ Close @ stream
        ];

        lookup = If[ TrueQ @ $snippetDebug, Lookup, Lookup[ #1, #2, "" ] & ];

        strings = ConfirmMatch[ lookup[ data, keys ], { __String }, "Result" ];

        If[ # === "", "", "# " <> StringDelete[ #, StartOfString~~"# " ] ] & /@ strings
    ] // LogChatTiming[ "GetStreamSnippets" ],
    throwInternalFailure
];

getStreamSnippets // endDefinition;


getStreamSnippets0 // beginDefinition;

getStreamSnippets0[ stream_InputStream, name_String, group_String, keys: { __String } ] := Enclose[
    Module[ { index, pos, len, wxf, snippets },
        index = ConfirmBy[ loadStreamIndex @ name, AssociationQ, "Index" ];
        { pos, len } = ConfirmMatch[ index @ group, { _Integer, _Integer }, "PositionAndLength" ];
        ConfirmMatch[ SetStreamPosition[ stream, pos ], pos, "SetStreamPosition" ];
        wxf = ConfirmBy[ ReadByteArray[ stream, len ], ByteArrayQ, "WXF" ];
        snippets = ConfirmBy[ BinaryDeserialize @ wxf, AssociationQ, "Snippets" ];
        KeyTake[ snippets, keys ]
    ],
    throwInternalFailure
];

getStreamSnippets0 // endDefinition;

(* ::**************************************************************************************************************:: *)
(* ::Subsubsection::Closed:: *)
(*loadStreamIndex*)
loadStreamIndex // beginDefinition;

loadStreamIndex[ name_String ] :=
    With[ { cached = $streamableSnippetIndexCache[ name, "Index" ] },
        cached /; AssociationQ @ cached
    ];

loadStreamIndex[ name_String ] := Enclose[
    ConfirmBy[ getStreamableSnippetsMetadata[ name ][ "Index" ], AssociationQ, "Index" ],
    throwInternalFailure
];

loadStreamIndex // endDefinition;

(* ::**************************************************************************************************************:: *)
(* ::Section::Closed:: *)
(*Package Footer*)
addToMXInitialization[
    $snippetDebug = False;
];

End[ ];
EndPackage[ ];
